config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: absolute
  link_on_import: absolute
  longkey: false
  showdiff: true
dotfiles:
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_config:
    src: config/i3/config
    dst: ~/.config/i3/config
  f_picom.conf:
    src: config/picom/picom.conf
    dst: ~/.config/picom/picom.conf
  d_rofi:
    src: config/rofi
    dst: ~/.config/rofi
  d_kitty:
    src: config/kitty
    dst: ~/.config/kitty
  f_condarc:
    src: condarc
    dst: ~/.condarc
profiles:
  base:
    dotfiles:
    - f_zshrc
    - f_gitconfig
  thor-endeavour:
    include:
    - base
    dotfiles:
    - f_config
    - f_picom.conf
    - d_rofi
    - d_kitty
  Brite-PF3VB0KC:
    include:
    - base
  odin:
    include:
    - base
    dotfiles:
    - f_config
    - f_condarc
