config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: absolute
  link_on_import: absolute
  longkey: false
  showdiff: true
dotfiles:
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
profiles:
  base:
    dotfiles:
    - f_zshrc
  thor-endeavour:
    dotfiles:
    - f_zshrc
