config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: absolute
  link_on_import: absolute
  longkey: false
  showdiff: true
dotfiles:
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_config:
    src: config/i3/config
    dst: ~/.config/i3/config
profiles:
  base:
    dotfiles:
    - f_zshrc
    - f_gitconfig
  thor-endeavour:
    include:
    - base
    dotfiles:
    - f_config
